# -*- coding: utf-8 -*-
"""Assignment day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4ww76mPdqvytpFadIfQ-qOHzXgs6TVm

Assignment 1(day 1)
"""

num1=('25')
print(num1)
print(type(num1))
num1=int('25')
print(type(num1))

#input task
num2=float(input("enter the value "))
print(num2)
num1=int(input("Enter the second value "))
print(num2)
add=float(num2+num1)
print(f"the sum of num1 and num2 is {add}")

def season(weather):
 result=input("enter the weather")
 return result
 print(result)
 if(weather==cold):
   print("weather is cold")
 else:
     print("weather is sunny")

list1 = [1,2,3,4]
list2 = list1
list1[1]=0
list1[3]=0
print(list2)

import time 
i=0
while(i<=10):
  print(i, end ='   ')
  time.sleep(1)
  i=i+1

